# Generated by Django 6.0.2 on 2026-02-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmodel',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_models/'),
        ),
    ]
